"""empty message

Revision ID: 0a9e0baf1242
Revises: ff1f5cc57c0a
Create Date: 2018-11-21 20:55:35.104753

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0a9e0baf1242'
down_revision = 'ff1f5cc57c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_info', sa.UnicodeText(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('default_info')

    # ### end Alembic commands ###
