"""empty message

Revision ID: 10c6e398f734
Revises: 36ef81a91426
Create Date: 2019-01-22 15:57:45.899087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10c6e398f734'
down_revision = '36ef81a91426'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hide_from_users', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('hide_from_users')

    # ### end Alembic commands ###
