"""empty message

Revision ID: 12eae4af655d
Revises: ceef2b443657
Create Date: 2019-05-06 18:15:34.056756

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '12eae4af655d'
down_revision = 'ceef2b443657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semesters',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.Unicode(length=2048), nullable=True),
                    sa.Column('color', sa.Unicode(length=32), nullable=True),
                    sa.Column('current', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'semesters', ['semester_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('semester_id')

    op.drop_table('semesters')
    # ### end Alembic commands ###
