"""empty message

Revision ID: 19ce60cb23c9
Revises: 51af68f8c7f8
Create Date: 2019-06-05 13:15:19.796094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ce60cb23c9'
down_revision = '51af68f8c7f8'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dont_want_back', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dont_want_back', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('dont_want_back')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('dont_want_back')

    # ### end Alembic commands ###
