"""empty message

Revision ID: 1a68cf42cc99
Revises: 05ef64240d95
Create Date: 2018-12-06 16:27:02.912395

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1a68cf42cc99'
down_revision = '05ef64240d95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('billing_rate', sa.Numeric(scale=2), nullable=True))
        batch_op.add_column(sa.Column('end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('payrate', sa.Numeric(scale=2), nullable=True))
        batch_op.add_column(sa.Column('start', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('start')
        batch_op.drop_column('payrate')
        batch_op.drop_column('end')
        batch_op.drop_column('billing_rate')
        batch_op.drop_column('active')

    # ### end Alembic commands ###
