"""empty message

Revision ID: 1d38a204080d
Revises: e8203259afc2
Create Date: 2018-11-26 16:37:35.363088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d38a204080d'
down_revision = 'e8203259afc2'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agreement', sa.UnicodeText(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('agreement')

    # ### end Alembic commands ###
