"""empty message

Revision ID: 242f3a7034a8
Revises: f01a2ef5a0a8
Create Date: 2019-02-22 20:13:11.564796

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '242f3a7034a8'
down_revision = 'f01a2ef5a0a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_messages',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('msgid', sa.Unicode(length=128), nullable=True),
                    sa.Column('phone_number', sa.BigInteger(), nullable=True),
                    sa.Column('msg', sa.Unicode(length=2048), nullable=True),
                    sa.Column('note', sa.Unicode(length=2048), nullable=True),
                    sa.Column('url_pic', sa.Unicode(length=2048), nullable=True),
                    sa.Column('date', sa.DateTime(), nullable=True),
                    sa.Column('status', sa.Unicode(length=64), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text_messages')
    # ### end Alembic commands ###
