"""empty message

Revision ID: 32de9ea5e060
Revises: 
Create Date: 2018-09-14 15:55:13.614441

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '32de9ea5e060'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_column('enrollments', 'teacher_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('teacher_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'enrollments', 'teachers', ['teacher_id'], ['id'])
    # ### end Alembic commands ###
