"""empty message

Revision ID: 559111379c8c
Revises: 39d0787b8a8f
Create Date: 2019-01-31 14:53:47.146537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559111379c8c'
down_revision = '39d0787b8a8f'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events_teachers',
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events_teachers')
    # ### end Alembic commands ###
