"""empty message

Revision ID: 7a3ef78eeccb
Revises: 1d38a204080d
Create Date: 2018-11-28 10:18:56.690950

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7a3ef78eeccb'
down_revision = '1d38a204080d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('timestamp')
        batch_op.drop_column('last_seen')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
