"""empty message

Revision ID: 7b72f0df2c7b
Revises: 19ce60cb23c9
Create Date: 2019-06-25 17:02:25.708108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b72f0df2c7b'
down_revision = '19ce60cb23c9'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_in_list', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.drop_column('show_in_list')

    # ### end Alembic commands ###
