"""empty message

Revision ID: 7c9d8cb946c4
Revises: 242f3a7034a8
Create Date: 2019-02-26 13:59:47.210442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c9d8cb946c4'
down_revision = '242f3a7034a8'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_note', sa.Unicode(length=2048), nullable=True))

    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('event_note')

    # ### end Alembic commands ###
