"""empty message

Revision ID: 7f24b274fb93
Revises: e69aa50454e6
Create Date: 2018-09-22 15:28:47.106983

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '7f24b274fb93'
down_revision = 'e69aa50454e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
