"""empty message

Revision ID: 81676dfdba86
Revises: 43224d9b6c62
Create Date: 2018-09-15 13:49:03.420927

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '81676dfdba86'
down_revision = '43224d9b6c62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachercontacts', schema=None) as batch_op:
        batch_op.drop_index('ix_teachercontacts_phone')

    op.drop_table('teachercontacts')
    with op.batch_alter_table('schoolcontacts', schema=None) as batch_op:
        batch_op.drop_index('ix_schoolcontacts_phone')

    op.drop_table('schoolcontacts')
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    op.create_table('schoolcontacts',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('note', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('email', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('phone', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('address1', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('address2', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('city', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('state', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('zip', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name='schoolcontacts_school_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='schoolcontacts_pkey')
                    )
    with op.batch_alter_table('schoolcontacts', schema=None) as batch_op:
        batch_op.create_index('ix_schoolcontacts_phone', ['phone'], unique=False)

    op.create_table('teachercontacts',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('note', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('email', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('phone', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('address1', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('address2', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('city', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('state', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('zip', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name='teachercontacts_teacher_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='teachercontacts_pkey')
                    )
    with op.batch_alter_table('teachercontacts', schema=None) as batch_op:
        batch_op.create_index('ix_teachercontacts_phone', ['phone'], unique=False)

    # ### end Alembic commands ###
