"""empty message

Revision ID: 846d248f57a4
Revises: e75bc2be97eb
Create Date: 2018-09-13 23:53:43.928932

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '846d248f57a4'
down_revision = 'e75bc2be97eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollments',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('class_id', sa.Integer(), nullable=True),
                    sa.Column('teacher_id', sa.Integer(), nullable=True),
                    sa.Column('student_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
                    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
                    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollments')
    # ### end Alembic commands ###
