"""empty message

Revision ID: 9cd9b6c4ec53
Revises: fbc6acd8f843
Create Date: 2018-10-29 10:43:50.962545

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9cd9b6c4ec53'
down_revision = 'fbc6acd8f843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_limit_from', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('age_limit_to', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('billing_rate', sa.Numeric(scale=2), nullable=True))
        batch_op.add_column(sa.Column('class_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('class_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('grade_limit_from', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('grade_limit_to', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payrate', sa.Numeric(scale=2), nullable=True))
        batch_op.add_column(sa.Column('registration_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('registration_start', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('registration_start')
        batch_op.drop_column('registration_end')
        batch_op.drop_column('payrate')
        batch_op.drop_column('grade_limit_to')
        batch_op.drop_column('grade_limit_from')
        batch_op.drop_column('class_start')
        batch_op.drop_column('class_end')
        batch_op.drop_column('billing_rate')
        batch_op.drop_column('age_limit_to')
        batch_op.drop_column('age_limit_from')

    # ### end Alembic commands ###
