"""empty message

Revision ID: 9d7cc316f148
Revises: 01978868721f
Create Date: 2018-09-15 02:35:51.021650

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '9d7cc316f148'
down_revision = '01978868721f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
                              existing_type=sa.VARCHAR(length=2048),
                              nullable=True)
        batch_op.alter_column('password',
                              existing_type=sa.VARCHAR(length=128),
                              nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
                              existing_type=sa.VARCHAR(length=128),
                              nullable=False)
        batch_op.alter_column('email',
                              existing_type=sa.VARCHAR(length=2048),
                              nullable=False)

    # ### end Alembic commands ###
