"""empty message

Revision ID: a1af6b9cd67f
Revises: 7b72f0df2c7b
Create Date: 2019-06-25 17:53:06.487173

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a1af6b9cd67f'
down_revision = '7b72f0df2c7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    migration_helper = op.create_table('notes',
                                       sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                                       sa.Column('student_id', sa.Integer(), nullable=True),
                                       sa.Column('timestamp', sa.DateTime(), nullable=True),
                                       sa.Column('text', sa.Unicode(length=2048), nullable=True),
                                       sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
                                       sa.PrimaryKeyConstraint('id')
                                       )
    # migrate data from enrollments to enrollments_migration
    conn = op.get_bind()
    res = conn.execute("select id, note from students")
    results = res.fetchall()
    migration_data = [{'student_id': r[0], 'text': r[1]}
                      for r in results]
    op.bulk_insert(migration_helper, migration_data)
    # delete old column
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))

    op.drop_table('notes')
    # ### end Alembic commands ###
