"""empty message

Revision ID: b5406599cadb
Revises: e61b1e58026c
Create Date: 2018-09-21 14:01:35.944894

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b5406599cadb'
down_revision = 'e61b1e58026c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Unicode(length=2048), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Unicode(length=2048), nullable=True))

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Unicode(length=2048), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Unicode(length=2048), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('note')

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('note')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('note')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
