"""empty message

Revision ID: bef68dcb42bb
Revises: f343749b43d6
Create Date: 2018-09-30 22:53:15.031306

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bef68dcb42bb'
down_revision = 'f343749b43d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
