"""empty message

Revision ID: c2528318af7a
Revises: 
Create Date: 2018-09-14 16:13:31.276473

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c2528318af7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.Unicode(length=2048), nullable=True),
                    sa.Column('director_name', sa.Unicode(length=2048), nullable=True),
                    sa.Column('note', sa.Unicode(length=2048), nullable=True),
                    sa.Column('current', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('subjects',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.Unicode(length=2048), nullable=True),
                    sa.Column('current', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('teachers',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('first_name', sa.Unicode(length=2048), nullable=True),
                    sa.Column('last_name', sa.Unicode(length=2048), nullable=True),
                    sa.Column('current', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('username', sa.Unicode(length=2048), nullable=True),
                    sa.Column('first_name', sa.Unicode(length=2048), nullable=True),
                    sa.Column('last_name', sa.Unicode(length=2048), nullable=True),
                    sa.Column('password_hash', sa.Unicode(length=128), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('classes',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('school_id', sa.Integer(), nullable=True),
                    sa.Column('teacher_id', sa.Integer(), nullable=True),
                    sa.Column('subject_id', sa.Integer(), nullable=True),
                    sa.Column('current', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
                    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
                    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('schoolcontacts',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('school_id', sa.Integer(), nullable=True),
                    sa.Column('note', sa.Unicode(length=2048), nullable=True),
                    sa.Column('email', sa.Unicode(length=2048), nullable=True),
                    sa.Column('phone', sa.Unicode(length=2048), nullable=True),
                    sa.Column('address1', sa.Unicode(length=2048), nullable=True),
                    sa.Column('address2', sa.Unicode(length=2048), nullable=True),
                    sa.Column('city', sa.Unicode(length=2048), nullable=True),
                    sa.Column('state', sa.Unicode(length=2048), nullable=True),
                    sa.Column('zip', sa.Unicode(length=2048), nullable=True),
                    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_schoolcontacts_phone'), 'schoolcontacts', ['phone'], unique=False)
    op.create_table('students',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('first_name', sa.Unicode(length=2048), nullable=True),
                    sa.Column('last_name', sa.Unicode(length=2048), nullable=True),
                    sa.Column('gender', sa.Boolean(), nullable=True),
                    sa.Column('dob', sa.DateTime(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('teachercontacts',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('teacher_id', sa.Integer(), nullable=True),
                    sa.Column('note', sa.Unicode(length=2048), nullable=True),
                    sa.Column('email', sa.Unicode(length=2048), nullable=True),
                    sa.Column('phone', sa.Unicode(length=2048), nullable=True),
                    sa.Column('address1', sa.Unicode(length=2048), nullable=True),
                    sa.Column('address2', sa.Unicode(length=2048), nullable=True),
                    sa.Column('city', sa.Unicode(length=2048), nullable=True),
                    sa.Column('state', sa.Unicode(length=2048), nullable=True),
                    sa.Column('zip', sa.Unicode(length=2048), nullable=True),
                    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_teachercontacts_phone'), 'teachercontacts', ['phone'], unique=False)
    op.create_table('usercontacts',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('note', sa.Unicode(length=2048), nullable=True),
                    sa.Column('email', sa.Unicode(length=2048), nullable=True),
                    sa.Column('phone', sa.Unicode(length=2048), nullable=True),
                    sa.Column('address1', sa.Unicode(length=2048), nullable=True),
                    sa.Column('address2', sa.Unicode(length=2048), nullable=True),
                    sa.Column('city', sa.Unicode(length=2048), nullable=True),
                    sa.Column('state', sa.Unicode(length=2048), nullable=True),
                    sa.Column('zip', sa.Unicode(length=2048), nullable=True),
                    sa.Column('contact_by_email', sa.Boolean(), nullable=True),
                    sa.Column('contact_by_txt', sa.Boolean(), nullable=True),
                    sa.Column('contact_by_mail', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_usercontacts_phone'), 'usercontacts', ['phone'], unique=False)
    op.create_table('enrollments',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('class_id', sa.Integer(), nullable=True),
                    sa.Column('student_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
                    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('events',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('class_id', sa.Integer(), nullable=True),
                    sa.Column('teacher_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
                    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_usercontacts_phone'), table_name='usercontacts')
    op.drop_table('usercontacts')
    op.drop_index(op.f('ix_teachercontacts_phone'), table_name='teachercontacts')
    op.drop_table('teachercontacts')
    op.drop_table('students')
    op.drop_index(op.f('ix_schoolcontacts_phone'), table_name='schoolcontacts')
    op.drop_table('schoolcontacts')
    op.drop_table('classes')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('teachers')
    op.drop_table('subjects')
    op.drop_table('schools')
    # ### end Alembic commands ###
