"""empty message

Revision ID: ceef2b443657
Revises: e1c1782c79f9
Create Date: 2019-04-29 20:20:31.247722

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ceef2b443657'
down_revision = 'e1c1782c79f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text_messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_messages',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('msgid', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
                    sa.Column('phone_number', sa.BIGINT(), autoincrement=False, nullable=True),
                    sa.Column('msg', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('note', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('url_pic', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
                    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('status', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='text_messages_pkey')
                    )
    # ### end Alembic commands ###
