"""empty message

Revision ID: d218acaf3d8c
Revises: 846d248f57a4
Create Date: 2018-09-13 23:58:11.496504

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd218acaf3d8c'
down_revision = '846d248f57a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_column('enrollments', 'teacher_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('teacher_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'enrollments', 'teachers', ['teacher_id'], ['id'])
    # ### end Alembic commands ###
