"""empty message

Revision ID: e1725493f5ac
Revises: 10c6e398f734
Create Date: 2019-01-31 14:22:11.274277

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e1725493f5ac'
down_revision = '10c6e398f734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    migration_helper = op.create_table('classes_teacher',
                                       sa.Column('teacher_id', sa.Integer(), nullable=True),
                                       sa.Column('class_id', sa.Integer(), nullable=True),
                                       sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
                                       sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], )
                                       )

    # migrate data from enrollments to enrollments_migration
    conn = op.get_bind()
    res = conn.execute("select id, teacher_id from classes")
    results = res.fetchall()
    migration_data = [{'class_id': r[0], 'teacher_id': r[1]}
                        for r in results]
    op.bulk_insert(migration_helper, migration_data)
    # delete old column
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('teacher_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.sa.Integer(), nullable=True))
        batch_op.create_foreign_key(['teacher_id'], ['teachers.id'], )

    op.drop_table('classes_teacher')
    # ### end Alembic commands ###
