"""empty message

Revision ID: e61b1e58026c
Revises: 81676dfdba86
Create Date: 2018-09-21 13:37:14.672120

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e61b1e58026c'
down_revision = '81676dfdba86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usercontacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.Unicode(length=2048), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usercontacts', schema=None) as batch_op:
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
