"""empty message

Revision ID: e69aa50454e6
Revises: b5406599cadb
Create Date: 2018-09-21 19:34:35.124533

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e69aa50454e6'
down_revision = 'b5406599cadb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools_users',
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('school_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
                    )
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_constraint('schools_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('schools_user_id_fkey', 'users', ['user_id'], ['id'])

    op.drop_table('schools_users')
    # ### end Alembic commands ###
