"""empty message

Revision ID: e75bc2be97eb
Revises: e8ac88eb267c
Create Date: 2018-09-08 17:24:23.372849

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e75bc2be97eb'
down_revision = 'e8ac88eb267c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('dob', sa.DateTime(), nullable=True))
    op.add_column('students', sa.Column('gender', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'gender')
    op.drop_column('students', 'dob')
    # ### end Alembic commands ###
