"""empty message

Revision ID: e8203259afc2
Revises: 72bd47ab5cda
Create Date: 2018-11-26 15:17:06.636247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8203259afc2'
down_revision = '72bd47ab5cda'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Unicode(length=2048), nullable=True))

    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
