"""empty message

Revision ID: eda082b3b0c4
Revises: 12eae4af655d
Create Date: 2019-05-28 14:06:56.811784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eda082b3b0c4'
down_revision = '12eae4af655d'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_name', sa.Unicode(length=2048), nullable=True))

    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('short_name')

    # ### end Alembic commands ###
