"""empty message

Revision ID: f343749b43d6
Revises: 8f8259edae3c
Create Date: 2018-09-30 20:45:48.222633

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f343749b43d6'
down_revision = '8f8259edae3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info', sa.Unicode(length=10240), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('info')

    # ### end Alembic commands ###
