"""empty message

Revision ID: f67c4f30d672
Revises: 9cd9b6c4ec53
Create Date: 2018-10-29 13:46:10.336037

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f67c4f30d672'
down_revision = '9cd9b6c4ec53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_time_end', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('class_time_start', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('class_time_start')
        batch_op.drop_column('class_time_end')

    # ### end Alembic commands ###
