"""empty message

Revision ID: ff1f5cc57c0a
Revises: c7a9098f5764
Create Date: 2018-11-20 09:31:37.991355

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ff1f5cc57c0a'
down_revision = 'c7a9098f5764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_of_week', sa.Unicode(length=2048), nullable=True))
    op.alter_column('classes', 'info', type_=sa.UnicodeText, existing_type=sa.Unicode(length=10240))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('day_of_week')
    op.alter_column('classes', 'info', type_=sa.Unicode(length=10240))
    # ### end Alembic commands ###
